### ISSUE TITLE
Janitor Monkey not cleaning up volumes

### ISSUE THREAD

**Issue by mcacker** [Netflix/SimianArmy#108]
Hi, I have quite a large number of detached volumes (> 1k), but the janitor monkey is not cleaning them up.  Looking at the logs, for each of the detached volumes it shows something like:

2013-12-18 17:17:29.479 - INFO  OldDetachedVolumeRule - [OldDetachedVolumeRule.java:107] Volume vol-43f5846a is not tagged with the Janitor meta information, ignore.

I've been unable to find out anything about what this means, and how to rectify it.  I would like the Janitor to cleanup volumes like this, does anyone know how?

thanks, Mitchell

**Comment by vishalbaghla** [comment]
Hi,

simianarmy.volumeTagging.enabled is set to true. but its not cleaning up resources. getting below log while running:
[1m> Building 75% > :jettyRun > Running at http://localhost:8080/simianarmy[22m[72D[0K2018-03-05 21:52:46.072 - INFO  OldDetachedVolumeRule - [OldDetachedVolumeRule.java:107] Volume vol-xxxxxx is not tagged with the Janitor meta information, ignore.

**Comment by valysin** [comment]
cccccccccc

**Comment by valysin** [comment]
Hi,

simianarmy.volumeTagging.enabled is set to true. but its not cleaning up resources. getting below log while running:
