### ISSUE TITLE
Archaius Support?

### ISSUE THREAD

**Issue by dstengle** [Netflix/SimianArmy#123]
Is there some reason the monkeys aren't using archaius instead of java.util.Properties? 

We now have to come up with some alternate method to configure per-environment rather than doing it just like every other app we have set up.

**Comment by ebukoski** [comment]
Internally at Netflix SimianArmy runs on top of [Karyon](https://github.com/Netflix/karyon) which itself is integrated with Archaius.  We extend some SimianArmy classes to read properties from Archaius. 

As noted above it isn't in the core SimianArmy for historical reasons.  We are actively eliminating as much internal-only SimianArmy code as possible so eventually we will integrate it directly but there is no timeline for this.
