### ISSUE TITLE
Document approaches/techniques used in non-public monkeys

### ISSUE THREAD

**Issue by mdwhatcott** [Netflix/SimianArmy#152]
[This press release](http://techblog.netflix.com/2011/07/netflix-simian-army.html) details several monkeys that don't seem to be included here (such as the latency monkey). If those monkeys could be open-sourced, great! If those monkeys must remain private, it would be great if the methods and techniques used to implement them could be documented here. Thanks for @benjchristensen for introducing me to the latency monkey in a recent presentation.

**Comment by ebukoski** [comment]
SimianArmy will continue to be Chaos, Janitor, and Conformity Monkey and documented here.

Latency Monkey evolved internally into the more robust Netflix Failure Injection Testing [FIT] (http://techblog.netflix.com/2014/10/fit-failure-injection-testing.html) project.  Unfortunately FIT has not been released as open source.

There is a separate open source project for [Security Monkey](https://github.com/Netflix/security_monkey). 

Some of the monkeys mentioned in the blog post (Doctor, 10-18) never came to reality.  Others (Chaos Gorilla) exist but have not been open sourced.
