### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by haozhenxiao** [Netflix/SimianArmy#153]
I've changed my JDK to 6, when running ./gradlew build, I got the following errors:
/SimianArmy/src/main/java/com/netflix/simianarmy/client/aws/chaos/ASGChaosCrawler.java:61: error: incompatible types: inference variable E has incompatible bounds
        return EnumSet.allOf(Types.class);
                            ^
    equality constraints: Types
    upper bounds: Enum<CAP#1>,Enum<E>
  where E is a type-variable:
    E extends Enum<E> declared in method <E>allOf(Class<E>)
  where CAP#1 is a fresh type-variable:
    CAP#1 extends Enum<CAP#1> from capture of ?
1 error
:compileJava FAILED

**Comment by ebukoski** [comment]
Closing this issue...it is old and SimianArmy has moved on to Java 7.
