### ISSUE TITLE
Rate Exceeded / Throttling Janitor Monkey

### ISSUE THREAD

**Issue by dannyviti** [Netflix/SimianArmy#173]
One of our AWS accounts is running Janitor Monkey daily and almost every day we get the following error:
com.amazonaws.AmazonServiceException: Rate exceeded (Service: AmazonCloudWatch; Status Code: 400; Error Code: Throttling; Request ID: c7248d1f-c116-11e4-a9a1-7fc9f8d26e2c)

Could there be a better way of handling this error in Simian Army? Perhaps a sleep/retry interval could be passed that if this error is encountered rather than error and exit, it'll sleep the appropriate amount of time and try again, until the rate limit clears.

Anyone else run into this and/or have suggestions?

**Comment by lantrix** [comment]
I just did a pull request to attempt to resolve this for Volume Tagging Monkey; seeing as it's always trying to tag volumes and ends up with heavy API call volume.

Are there any other places this happened for you?

**Comment by dannyviti** [comment]
Sorry for the slow reply, we were seeing this error pretty regularly, however it's been running pretty smoothly for the past several runs. I'll keep watching and if it shows up again I'll post an update.

**Comment by ebukoski** [comment]
This was discussed in PR #190 and a retry was added with commit 4f22e38f02d2ae785e1d418e4708b95ec94e9cc3.
