### ISSUE TITLE
Make Janitor Monkey OWNER_TAG_KEY configurable

### ISSUE THREAD

**Issue by johnjelinek** [Netflix/SimianArmy#178]
We use `Owner` instead of `owner`. This should be configurable.

**Comment by lantrix** [comment]
We use the same TitleCase style tag key. To this end; I've implemented this to be configurable in the `janitor.properties` config file. It will fall back to `owner` if not set.

**Comment by lantrix** [comment]
Actually there are few more Hard Coded uses of `resource.getTag("creator");` and `resource.getTag("owner");`
I'll do another commit; and re-do another pull request.

**Comment by lantrix** [comment]
@johnjelinek I see pull #191 implemented this this week. We have been using this internally since May this year. Good to see it's now in the main code.
