### ISSUE TITLE
Killprocess doesnt kill the process in instance

### ISSUE THREAD

**Issue by ambikanair1990** [Netflix/SimianArmy#179]
Hi All,

I am trying to test the "KillProcess" failure in my set up. Killprocess.sh files have the following code:

#!/bin/bash
# Script for KillProcesses Chaos Monkey

cat << EOF > /tmp/kill_loop.sh
#!/bin/bash
while true;
do
    pkill -KILL -f java
    pkill -KILL -f python
    sleep 1
done
EOF

nohup /bin/bash /tmp/kill_loop.sh &

I can still see Java and python process running in the instance even after this failure is injected. 
I tried to add additional process like calculator. It doesnt work as expected. When I manually execute the file, I can see the process getting killed. 

Please could anyone suggest if I should make any code changes.

Thanks

**Comment by gorzell** [comment]
Were you able to resolve this?

**Comment by ambikanair1990** [comment]
I found out that it takes some time to kill the processes in the instances. varries from 15-20 minutes. I didnt change any  code.

**Comment by archthegit** [comment]
How re you checking if the process is running or not
