### ISSUE TITLE
Support for notification via SNS

### ISSUE THREAD

**Issue by rvedotrc** [Netflix/SimianArmy#182]
It seems odd that the only notification of terminations is via SES, not SNS.

Suggested feature: for each termination, send a JSON message to some configured SNS topic, including at least the instance id terminated, and the arn of the Autoscaling Group of which it was a member.

**Comment by lantrix** [comment]
I was looking for the same thing. Currently implementing this in my fork as well. If I get it working anytime soon I'll do a pull request.

**Comment by lytonyt** [comment]
Hi Lantrix,

Any updates on this implementations? This is something that would useful in my infrastructure setup as well.

Regards,
Tony

**Comment by mlafeldt** [comment]
Supporting SNS would indeed be cool as it'd allow sending notifications to Slack etc.

I'm also thinking about a different approach: writing a small (Go) service that forwards events returned by the REST API to SNS, Slack, etc.

**Comment by lantrix** [comment]
We had just stuck with email notifications, as we decided to re-write the SimianArmy components we are using as AWS lambda functions; so no further improvements on the code at this time.

**Comment by algra** [comment]
@lantrix it would be great if you can open-source it after it will reach some more or less usable state.

**Comment by algra** [comment]
but i afraid this is out of scope for this issue/repo ;)

**Comment by algra** [comment]
Actually email is quite sufficient for some cases, for example: Slack has an email integration, and you can put emails to SNS using emails sent to SES.

**Comment by mlafeldt** [comment]
@algra Slack does indeed have an email integration. Thanks for the tip!

**Comment by rvedotrc** [comment]
Open Source Lambda-based Chaos-Monkey-like functionality: https://github.com/bbc/chaos-lambda

**Comment by lantrix** [comment]
@algra despite deciding to re-write using lamda; we are still using SimianArmy as of today. If I get tasked to re-work on that I'll make sure SNS is at the top of my list -> as we would also use that to push to Lambda and publish to slack instead of the email trail we get now.

**Comment by rvedotrc** [comment]
We're currently using a Lambda hook from CloudTrail to generate SNS notifications of _any_ terminations of ec2 instances (whether by Chaos Monkey, or chaos-lambda, or whatever).  Thus, the lack of SNS output from Chaos Monkey is now a non-issue for us.

Seems to be a far nicer approach.

**Comment by tatonki1** [comment]
@rvedotrc - could you share with me how you setup your Lambda function to monitor the cloudtrail log for api calls when any of your auto-scaling groups have an ec2 termination, please?  I'm a lambda novice, and am unable to utilize the simian army built in AWS:SES email notifications outside of the sandbox env as i don't have console access to verify my source/dest emails in nonProd envs...so am very interested in your work around.  Thank you!!
