### ISSUE TITLE
Gradle Build Failure

### ISSUE THREAD

**Issue by mwhite14** [Netflix/SimianArmy#184]
[DEBUG] [org.gradle.configuration.project.BuildScriptProcessor] Timing: Running the build script took 3.716 secs
[ERROR] [org.gradle.BuildExceptionReporter]
[ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
[ERROR] [org.gradle.BuildExceptionReporter]
[ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
[ERROR] [org.gradle.BuildExceptionReporter] nebula/plugin/netflixossproject/NetflixOssProjectPlugin : Unsupported major.minor version 51.0
[ERROR] [org.gradle.BuildExceptionReporter]
[ERROR] [org.gradle.BuildExceptionReporter] * Try:
[ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.
[LIFECYCLE] [org.gradle.BuildResultLogger]
[LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
[LIFECYCLE] [org.gradle.BuildResultLogger]
[LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 6.445 secs

java version "1.6.0_45"
Java(TM) SE Runtime Environment (build 1.6.0_45-b06)
Java HotSpot(TM) 64-Bit Server VM (build 20.45-b01, mixed mode)

**Comment by rspieldenner** [comment]
Our grade plugins require JDK7 to run. I believe Simian Army will still
target JDK6 bytecode when producing a jar.

**Comment by mwhite14** [comment]
You may want to update the Wiki, it says to use JDK6 to build.

https://github.com/Netflix/SimianArmy/wiki/Quick-Start-Guide#build-the-monkeys-with-gradle

**Comment by kentpak** [comment]
I had the same issue with java version "1.7.0_71"
Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.71-b01, mixed mode)

Logs:-
Download http://plugins.gradle.org/m2/com/googlecode/javaewah/JavaEWAH/0.7.9/JavaEWAH-0.7.9.pom
Download http://plugins.gradle.org/m2/org/apache/httpcomponents/httpcore/4.2.4/httpcore-4.2.4.pom
Download http://plugins.gradle.org/m2/org/apache/httpcomponents/httpcomponents-core/4.2.4/httpcomponents-core-4.2.4.pom

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'simianarmy'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve com.netflix.nebula:nebula-project-plugin:2.2.0.
     Required by:
         :simianarmy:unspecified > com.netflix.nebula:gradle-netflixoss-project-plugin:2.2.9
      > Could not GET 'http://plugins.gradle.org/m2/com/netflix/nebula/nebula-project-plugin/2.2.0/nebula-project-plugin-2.2.0.pom'.
         > The target server failed to respond

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by kentpak** [comment]
The recent jenkins build failed as well.
https://netflixoss.ci.cloudbees.com/job/SimianArmy-master/

**Comment by mwhite14** [comment]
I had no further issues after moving to java 1.7.0_80

**Comment by ebukoski** [comment]
I bumped the cloudbees jenkins build to 1.7.  It is working now.

Rob updated the wiki.

**Comment by vishnudxb** [comment]
Even the Gradle build fails for JDK8 however its working fine with JDK7

**Comment by mwhite14** [comment]
I noticed the same thing.
