### ISSUE TITLE
Gradle build Failed

### ISSUE THREAD

**Issue by kentpak** [Netflix/SimianArmy#186]
I have just clone a copy of SimianArmy from github and trigger a ./gradlew build -x test. The job failed with:-

Inferred version: 2.5.0-SNAPSHOT

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'simianarmy'.
> Failed to notify project evaluation listener.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Any help would be appreciated.

**Comment by alfasin** [comment]
I just built it two days ago and it worked for me.
Please do as Gradle suggests and run it again with "--stacktrace", "--info"
or "--debug" then go over the output and look for errors.

When you have a concrete error that you don't know how to handle - post it
here.

Thanks,
Nir
