### ISSUE TITLE
Janitor Monkey Using Edda - Snapshot Issue

### ISSUE THREAD

**Issue by mwhite14** [Netflix/SimianArmy#192]
When using Edda with Janitor Monkey, Janitor Monkey is flagging Snapshots that are not mine, but also ones that have the following properties:   "ownerAlias":"amazon","ownerId":"947081328633".

Janitor monkey flagged about 5000 Snapshots that are not even in my account.

**Comment by ebukoski** [comment]
Did you set your owner ID property?  Look in janitor.properties:

# The owner id that snapshots have for being managed by Janitor Monkey. This property needs
# to set if you use Edda for getting snapshots to avoid getting shared snapshots. If you are using
# AWS to get the snapshots, this property does not need to be set.
#simianarmy.janitor.snapshots.ownerId = 012345678

**Comment by mwhite14** [comment]
Wow, can't believe I overlooked that property.
