### ISSUE TITLE
changes to log4j.properties don't have any effect?

### ISSUE THREAD

**Issue by dx-pbuckley** [Netflix/SimianArmy#207]
I tried modifying `./src/main/resources/log4j.properties` but it doesn't seem to have any effect - I read somewhere that there is an slf4j -> log4j binding/adapter, is there something else I need to do other than modify the log4j.properties in order to get SimianArmy logging to a file?

Here's an example log4j.properties I tried using, but it didn't do anything (admittedly, I'm not familiar with log4j). I also tried changing the `log4j.appender.stdout.layout.ConversionPattern` to see if I could get anything to happen with log4j.properties, but it still had no impact on the logging output. Any tips or something I'm missing about logging for SimianArmy?

```
     log4j.rootLogger=INFO, stdout, R

     # stdout
     log4j.appender.stdout=org.apache.log4j.ConsoleAppender
     log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
     log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss.SSS} - %-5p %C{1} - [%F:%L] %m%n
     
     # file
     log4j.appender.R=org.apache.log4j.RollingFileAppender
     log4j.appender.R.File=/var/log/simianarmy/simianarmy.log
     log4j.appender.R.MaxFileSize=900KB
     # Keep one backup file
     log4j.appender.R.MaxBackupIndex=3
     
     log4j.appender.R.layout=org.apache.log4j.PatternLayout
     log4j.appender.R.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss.SSS} - %-5p %C{1} - [%F:%L] %m%n
```

**Comment by ebukoski** [comment]
Your config looks fine.  

Two things to look at: make sure the running process can write to /var/log/simianarmy/simianarmy.log and make sure you rebuilt a war (or whatever else you are doing to re-deploy) after you edit log4j.properties in ./src.

**Comment by dx-pbuckley** [comment]
Thanks @ebukoski, I double checked and started up a fresh ec2 instance (2015.03 Amazon linux AMI) where I'm setting up SimianArmy. I'm running `./gradelw jettyRun` as the user `simian` in the group `simian`, which has permissions and is owner of /var/log/simianarmy. I've modified the log4j.properties before I build the war file. Anything else I should check?

The reason I think changing log4j.properties is having no effect is because I've also tried changing the log4j.appender.stdout.ConversionPattern, and that doesn't reflect anything in what I see in stdout on the console.

Some commands on the console:
```
[simian@172 SimianArmy]$ java -version
java version "1.7.0_85"
OpenJDK Runtime Environment (amzn-2.6.1.3.61.amzn1-x86_64 u85-b01)
OpenJDK 64-Bit Server VM (build 24.85-b03, mixed mode)
[simian@172 SimianArmy]$ cat src/main/resources/log4j.properties 
log4j.rootLogger=INFO, stdout, R

# stdout
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
# I changed this from the default, but I don't see it doing anything
log4j.appender.stdout.layout.ConversionPattern=%-5p %C{1} - [%F:%L] %m%n - %d{yyyy-MM-dd HH:mm:ss.SSS} -

# I see /var/log/simianarmy/simianarmy.log created, but it's empty
# file
log4j.appender.R=org.apache.log4j.RollingFileAppender
log4j.appender.R.File=/var/log/simianarmy/simianarmy.log
log4j.appender.R.MaxFileSize=900KB
# Keep three backup files
log4j.appender.R.MaxBackupIndex=3

log4j.appender.R.layout=org.apache.log4j.PatternLayout
log4j.appender.R.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss.SSS} - %-5p %C{1} - [%F:%L] %m%n
[simian@172 SimianArmy]$ ls -l /var/log | grep simian
drwxr-xr-x 2 simian simian   4096 Aug 20 16:20 simianarmy
[simian@172 SimianArmy]$ whoami
simian
[simian@172 SimianArmy]$ ls -l /var/log/simianarmy/
total 0
-rw-rw-r-- 1 simian simian 0 Aug 20 16:20 simianarmy.log
```

And this is the output I'm seeing on stdout/console, which doesn't seem to be reflecting my format changes to the stdout appender:
```
16:20:54.000 [pool-2-thread-1] INFO  c.n.s.a.janitor.VolumeTaggingMonkey - Volume tagging monkey is leashed. No real change is made to the volume.
16:20:54.001 [pool-2-thread-1] INFO  c.n.s.a.janitor.VolumeTaggingMonkey - Setting tag JANITOR_META to 'instance=i-58851ef3;owner=;detachTime=' for volume vol-283cd2c5
16:20:54.001 [pool-2-thread-1] INFO  c.n.s.a.janitor.VolumeTaggingMonkey - Volume tagging monkey is leashed. No real change is made to the volume.
16:20:54.001 [pool-2-thread-1] INFO  c.n.s.a.janitor.VolumeTaggingMonkey - Setting tag JANITOR_META to 'instance=i-66a03bcd;owner=;detachTime=' for volume vol-d609e73b
16:20:54.012 [pool-2-thread-1] INFO  c.n.s.a.janitor.VolumeTaggingMonkey - Volume tagging monkey is leashed. No real change is made to the volume.
16:20:54.012 [pool-2-thread-1] INFO  com.netflix.simianarmy.Monkey - Reporting what I did...
```

**Comment by dx-pbuckley** [comment]
I also confirmed I could compile an example jar-with-dependences using maven, and then gradle - both sample projects had no problem with the identical log4j.properties, logging to both stdout and my file `/var/log/simianarmy/simianarmy.log`. Seems like that would rule out most permissions or OS environment issues. I tested both jars on OSX and the Amazon Linux EC2 instance. It seems like this problem is specific to SimianArmy - is anyone there using it with java 1.7 (AZL EC2 default) or java 1.8 (what I have on OSX) and/or trying to log to a file? I know I could easily redirect stdout & stderr in an /etc/init.d startup script for SimianArmy but the log4j.properties seems like the "correct" way to do it and I'd like to use that if possible.

**Comment by dx-pbuckley** [comment]
I tried using java 1.6 but that seems to be a non-starter (error below). Is there anyone who has tried modifying log4j.properties or logging it to a file? I've spent a fair amount of time on it, different permutations, simple minimally viable cases to confirm it is an issue with SimianArmy and not my setup. Hopefully that gives you what you need to fix it - I'm just going to have my /etc/init.d/simianarmy script redirect stdout/stderr to a file and logrotate it.

```
FAILURE: Build failed with an exception.

* What went wrong:
nebula/plugin/netflixossproject/NetflixOssProjectPlugin : Unsupported major.minor version 51.0

```

**Comment by algra** [comment]
I've found the problem, it's happening because of two loggers are used as dependencies:
**logback** https://github.com/Netflix/SimianArmy/blob/master/build.gradle#L50
and
**slf4j-log4j12** https://github.com/Netflix/SimianArmy/blob/master/build.gradle#L56
while configuration is existing only for the second one. At runtime, **logback** is used.

I have no ideas why **logback** was added as dependency, because no one except **cobertura** is using it and **cobertura** is just for generating test coverage, which has nothing to do with runtime.

I'll create a pull request in a second removing this dependency.
