### ISSUE TITLE
wiki updates

### ISSUE THREAD

**Issue by dx-pbuckley** [Netflix/SimianArmy#209]
I found a couple out of date sentences on the wiki, but I don't think I can contribute to edit it with a PR?

I think this sentence should be removed since there are multiple monkeys in Simian Army now:
`Since there is only one monkey currently in the Simian Army anything more than 1 is not useful at the moment.`

The link to possible timezone values is no longer valid: `http://docs.oracle.com/cd/E19653-01/819-4438/acfib/index.html` gives me a 404 from Oracle. Seems like `https://docs.oracle.com/cd/E26401_01/doc.122/e20929/T319774T319789.htm` should be the new link.

**Comment by ebukoski** [comment]
Updated both.  Thanks!
