### ISSUE TITLE
Cleaning up launch configurations?

### ISSUE THREAD

**Issue by sommestad** [Netflix/SimianArmy#214]
Thanks for an awesome open source lib. :clap: 

When JanitorMonkey was first launched, [it was said](http://techblog.netflix.com/2013/01/janitor-monkey-keeping-cloud-tidy-and.html) that there would be support for having JanitorMonkey clean up launch configs too:

> In the near future we are planning to release some new resource types for Janitor Monkey to manage. As mentioned earlier, the next candidate will likely be launch configuration. 

Whatever happened to that? :smile: 

It would be very much appreciated, as it's a hassle to clean them up yourself.

**Comment by ebukoski** [comment]
Janitor cleans launch configurations:

https://github.com/Netflix/SimianArmy/wiki/Janitor-Settings#setting-rule-of-cleaning-up-launch-configurations

https://github.com/Netflix/SimianArmy/blob/master/src/main/java/com/netflix/simianarmy/aws/janitor/LaunchConfigJanitor.java
