### ISSUE TITLE
Eureka Client used by Conformity Monkey needs to be updated

### ISSUE THREAD

**Issue by ebukoski** [Netflix/SimianArmy#238]
The Eureka Client used by Conformity Monkey needs to be updated.  

The current client version is 1.1.22 which dates to Dec 7, 2012.  Among the features in the new client is updated getHealthCheckUrl() method that also supports secure health check URLs.

**Comment by mlafeldt** [comment]
@ebukoski I think you can close this issue as you've merged c93b350 already.
