### ISSUE TITLE
Wiki contributions

### ISSUE THREAD

**Issue by mlafeldt** [Netflix/SimianArmy#252]
Hey,

Is there any chance that I (or anybody) can have write access to the Wiki? It's currently restricted to collaborators.

AFAIK, there's currently no way to contribute improvements to the documentation (I saw quite a few typos), which is less than perfect for an open source project.

**Comment by ebukoski** [comment]
Unfortunately we can't open it up to general editing.  There isn't a way to
review changes before they are published so the pages would be vulnerable
to spam, phishing, and other random mischief.

Not the best solution but if you open a github issue with the changes to be
made a contributor will make the updates.

**Comment by mlafeldt** [comment]
You know this isn't going to happen. Most people (including me) won't make the effort to diff the Wiki and paste the diff into an issue so that someone else can apply it.

You could at least add individual people as collaborators (based on GitHub history etc.) to avoid spam.

PS: We wouldn't have this discussion if the documentation were a part of the repo itself.
