### ISSUE TITLE
Support for non-US holidays

### ISSUE THREAD

**Issue by algra** [Netflix/SimianArmy#258]
Hi,

We would like to have support for some open & free holiday API for retrieving non-US holidays (e.g. holidayapi.com, which was one of first Google results or similar) or possibility to customise it in config file.

Reason for that is holidays in each country are different, so chaos monkey killing stuff also on german (in our case) holidays, which is not the thing most people want. For now, without thinking about it a lot, I would say, loading from config file would be better if we want to have monkey disabled on days which are not official holidays, but when most people are not working anyway.

@ebukoski, what do you think about it? We will take care of implementation if you're ok with merging PR with such feature.

**Comment by ebukoski** [comment]
I can definitely review and merge a PR for alternate calendars.

Perhaps the calendar should be controlled through a property setting?
Something like:

     simianarmy.calendar.class=com.netflix.simianarmy.basic.GermanCalendar

SimianArmyContext.java
<https://github.com/Netflix/SimianArmy/blob/master/src/main/java/com/netflix/simianarmy/basic/BasicSimianArmyContext.java#L126>
would
need to be modified to read props and load the calendar class.  But once in
place it would allow for multiple different calendars.

**Comment by algra** [comment]
Yea, that would be another possibility, but in this case you will have to compile it when you change a holiday.

I'll think about it a couple of days and will give you an update :)
