### ISSUE TITLE
Defined monkey time never works - "Not Time for CHAOS Monkey"

### ISSUE THREAD

**Issue by MihailStopnik** [Netflix/SimianArmy#264]
Hi,

I need to run monkey all day except of 14:00 - 16:00 time slot, so I set:
simianarmy.calendar.openHour = 16
simianarmy.calendar.closeHour = 14

and I see that monkey starts every hour but throws 'Not Time for CHAOS Monkey' message. 
I suppose that happens because  'openHour' biggest than 'closeHour' and runsPerDay gets unexpected value.

long units = freqUnit.convert(close.getTimeInMillis() - open.getTimeInMillis(), TimeUnit.MILLISECONDS);
runsPerDay = units / ctx.scheduler().frequency();
https://github.com/Netflix/SimianArmy/blob/4e2426d79a7482075ce3af3f23c89ce9274786b6/src/main/java/com/netflix/simianarmy/basic/chaos/BasicChaosMonkey.java#L97

Is this expected behavior? Thank you!

**Comment by ebukoski** [comment]
You are correct, openHour > closeHour means it never runs.  That was a
clever try but Monkeys aren't that smart  :)

You will need to roll code to have an exclusion window.  Or you could just
set it to run before the window, openHour=0, closeHour=14.

This is really hacky but you could have two monkeys, one with openHour=0,
closeHour=14 and a second with openHour=16, closeHour=23.

**Comment by MihailStopnik** [comment]
Thank you for response. Resolved :)
