### ISSUE TITLE
Jonitor and Chaos monkey configuration

### ISSUE THREAD

**Issue by santoshpatha12** [Netflix/SimianArmy#267]
Hi All,

I am trying to install and explore Janitor and Chaos monkey tools.

Can someone send detailed document for installation and configuration, usage

I want to use either RHEL/Windows system to configure

Regards,
Santosh

**Comment by ralsu091** [comment]
https://github.com/Netflix/SimianArmy/wiki

**Comment by petr-tik** [comment]
The issue looks closed to me
