### ISSUE TITLE
maven support?

### ISSUE THREAD

**Issue by froderick** [Netflix/SimianArmy#279]
Would you accept a pull request that included a pom.xml for convenient builds with maven?

**Comment by mgeis** [comment]
Is Gradle so inconvenient?  Out of curiosity, what's the (broad) use case for this PR?  There's not a lot of demand for this, and I'm struggling to think of anything Maven can do for the project that Gradle cannot.  If you really need Maven, you can always just make a fork, and keep it in sync with the master (which I'm sure is what you've done so far).

**Comment by froderick** [comment]
The work adds support for sending events to an SNS topic when chaos monkey terminates instances. Had some trouble puzzling out a problem with adding an SNS dependency, just switched to maven to avoid being blocked. 

I concede that adding maven build doesn't add much value to the project. It merely makes it a bit easier to get started hacking on it for the people familiar with maven and not gradle. Sounds like you're not a fan, so I'll switch back to gradle once I have my changes ready.
