### ISSUE TITLE
support microservice running on  Kubernetes  cluster ? 

### ISSUE THREAD

**Issue by BruceZu** [Netflix/SimianArmy#289]
Hi all,
Can i run chaos monkey on a microservice architecture runing on Kubernetes ? there is any stating guides or tutorials to how to do this ?

Thank you

**Comment by BruceZu** [comment]
https://github.com/mlafeldt/docker-simianarmy/issues/2

**Comment by cfieber** [comment]
the current version of [chaos monkey](https://github.com/Netflix/chaosmonkey) uses [Spinnaker](http://spinnaker.io) as its back end for cloud management operations and application metadata. Spinnaker supports managing kubernetes clusters.
