### ISSUE TITLE
terminate on demand configuration problem

### ISSUE THREAD

**Issue by endwall** [Netflix/SimianArmy#59]
Did anyone try on demand termination? I think there is a typo between configuration property and BasicChaosMonkey.java.

In configuration property chaos.properties,the sample property is 
//## on-demand termination of chaos monkey
//##simianarmy.chaos.terminationOndemand.enabled = false

while in the java code, it is
Line 123:        String prop = NS + "terminateOndemand.enabled";

check the word "termination" and "terminate".

**Comment by ebukoski** [comment]
Closed ... no longer an issue, there are no "terminationOndemand" properties in the source.
