### ISSUE TITLE
Gradle Build Failure - Installation failure

### ISSUE THREAD

**Issue by croess** [Netflix/SimianArmy#67]
If i follow the installation guide, the installation fails on a Ubuntu 12.04 LTS server.

./gradlew build

warning: [options] bootstrap class path not set in conjunction with -source 1.6
error: warnings found and -Werror specified
1 error
1 warning

FAILURE: Build failed with an exception.

Running ./gradlew build --debug:

14:51:26.467 [INFO] [org.gradle.api.internal.tasks.compile.jdk6.Jdk6JavaCompiler] Compiling with JDK 6 Java compiler API.
14:51:27.587 [ERROR] [system.err] warning: [options] bootstrap class path not set in conjunction with -source 1.6
14:51:27.652 [ERROR] [system.err] error: warnings found and -Werror specified
14:51:27.655 [ERROR] [system.err] 1 error
14:51:27.657 [ERROR] [system.err] 1 warning
14:51:27.684 [DEBUG] [org.gradle.logging.internal.DefaultLoggingConfigurer] Finished configuring with level: DEBUG, configurers: [org.gradle.logging.internal.OutputEventRenderer@47ef303b, org.gradle.logging.internal.logback.LogbackLoggingConfigurer@28479662, org.gradle.logging.internal.JavaUtilLoggingConfigurer@73e21096]

$JAVA_HOME is set correctly. Can you help me here?

**Comment by ebukoski** [comment]
Closing this issue as SimianArmy has updated build/install code now.  Please open a new issue if you have a recent build issue.
