### ISSUE TITLE
Compiling Java 6 bytecode using Java 7

### ISSUE THREAD

**Issue by dipthegeezer** [Netflix/SimianArmy#74]
Hi Michael

We've just rolled out Java 7 across most of our instances and are aiming to move towards that and have hit a snag when working with Simian Army. It's more related to gradle but wondered if you might have a few ideas on resolving it. We get the following error when we try to compile:

```
:compileJavawarning: [options] bootstrap class path not set in conjunction with -source 1.6
```

We have a few work arounds;
* disabling warnings as errors seems to work
* Also setting java_home explicitly to java6.
* There is also some talk on the inter-web about setting the bootstrapclasspath.

If you have some suggestions we'd appreciate it.

Thanks.

Dip

**Comment by ebukoski** [comment]
These warnings no longer occur.
