### ISSUE TITLE
Is opting out of the janitor persistent across SimianArmy restart?

### ISSUE THREAD

**Issue by mcacker** [Netflix/SimianArmy#78]
I thought I had opted out of an ASG being cleaned up:

curl http://localhost:8080/simianarmy/api/v1/janitor -d '{"eventType":"OPTOUT","resourceId":"ct_engine-CTE-133-20130711124528"}'

but at some point the ASG was removed.  I stop and start SimianArmy frequently (we turn off most of our dev & qa apps during non-work hours), and I was wondering if the problem was that such an opt out is not persistent across restarts?

thanks, Mitchell

**Comment by ebukoski** [comment]
Opt-outs are stored in SimpleDB so are persisted across restarts.
